language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino_sketch/ardas.ino

install:
    - pip install -U platformio

    # Libraries from PlatformIO Library Registry:
    # http://platformio.org/#!/lib/show/83/RTC
    - platformio lib install 83

script:
    - platformio ci --board=uno --lib="." arduino_sketch/ardas.ino